// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.3
// source: myb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_myb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{0}
}

type AudioProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WindowTitle   string                 `protobuf:"bytes,3,opt,name=window_title,json=windowTitle,proto3" json:"window_title,omitempty"`
	CurrentVolume float32                `protobuf:"fixed32,4,opt,name=current_volume,json=currentVolume,proto3" json:"current_volume,omitempty"` // 0.0 ~ 1.0
	IsMeetingApp  bool                   `protobuf:"varint,5,opt,name=is_meeting_app,json=isMeetingApp,proto3" json:"is_meeting_app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioProcess) Reset() {
	*x = AudioProcess{}
	mi := &file_myb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioProcess) ProtoMessage() {}

func (x *AudioProcess) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioProcess.ProtoReflect.Descriptor instead.
func (*AudioProcess) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{1}
}

func (x *AudioProcess) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AudioProcess) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AudioProcess) GetWindowTitle() string {
	if x != nil {
		return x.WindowTitle
	}
	return ""
}

func (x *AudioProcess) GetCurrentVolume() float32 {
	if x != nil {
		return x.CurrentVolume
	}
	return 0
}

func (x *AudioProcess) GetIsMeetingApp() bool {
	if x != nil {
		return x.IsMeetingApp
	}
	return false
}

type ProcessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*AudioProcess        `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessList) Reset() {
	*x = ProcessList{}
	mi := &file_myb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessList) ProtoMessage() {}

func (x *ProcessList) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessList.ProtoReflect.Descriptor instead.
func (*ProcessList) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessList) GetProcesses() []*AudioProcess {
	if x != nil {
		return x.Processes
	}
	return nil
}

type KeywordMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      []string               `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Threshold     float64                `protobuf:"fixed64,2,opt,name=threshold,proto3" json:"threshold,omitempty"` // 0.0 ~ 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordMatch) Reset() {
	*x = KeywordMatch{}
	mi := &file_myb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordMatch) ProtoMessage() {}

func (x *KeywordMatch) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordMatch.ProtoReflect.Descriptor instead.
func (*KeywordMatch) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{3}
}

func (x *KeywordMatch) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *KeywordMatch) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type PolicyAction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Volume          uint32                 `protobuf:"varint,1,opt,name=volume,proto3" json:"volume,omitempty"`                                          // 0 ~ 100
	DurationSeconds uint32                 `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // keep volume for N seconds after last hit
	Then            string                 `protobuf:"bytes,3,opt,name=then,proto3" json:"then,omitempty"`                                               // "auto" | "mute"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolicyAction) Reset() {
	*x = PolicyAction{}
	mi := &file_myb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyAction) ProtoMessage() {}

func (x *PolicyAction) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyAction.ProtoReflect.Descriptor instead.
func (*PolicyAction) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{4}
}

func (x *PolicyAction) GetVolume() uint32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PolicyAction) GetDurationSeconds() uint32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *PolicyAction) GetThen() string {
	if x != nil {
		return x.Then
	}
	return ""
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Match         *KeywordMatch          `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	Action        *PolicyAction          `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_myb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{5}
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetMatch() *KeywordMatch {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *Policy) GetAction() *PolicyAction {
	if x != nil {
		return x.Action
	}
	return nil
}

type PolicyYaml struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yaml          string                 `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyYaml) Reset() {
	*x = PolicyYaml{}
	mi := &file_myb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyYaml) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyYaml) ProtoMessage() {}

func (x *PolicyYaml) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyYaml.ProtoReflect.Descriptor instead.
func (*PolicyYaml) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{6}
}

func (x *PolicyYaml) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

type ValidationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_myb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{7}
}

func (x *ValidationResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidationResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Policies      []*Policy              `protobuf:"bytes,2,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionReq) Reset() {
	*x = StartSessionReq{}
	mi := &file_myb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionReq) ProtoMessage() {}

func (x *StartSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionReq.ProtoReflect.Descriptor instead.
func (*StartSessionReq) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{8}
}

func (x *StartSessionReq) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StartSessionReq) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type SessionRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRef) Reset() {
	*x = SessionRef{}
	mi := &file_myb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRef) ProtoMessage() {}

func (x *SessionRef) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRef.ProtoReflect.Descriptor instead.
func (*SessionRef) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{9}
}

func (x *SessionRef) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // "idle" | "listening" | "triggered" | "paused"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_myb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{10}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Session) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type SetVolumeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Volume        uint32                 `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"` // 0 ~ 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVolumeReq) Reset() {
	*x = SetVolumeReq{}
	mi := &file_myb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVolumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVolumeReq) ProtoMessage() {}

func (x *SetVolumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVolumeReq.ProtoReflect.Descriptor instead.
func (*SetVolumeReq) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{11}
}

func (x *SetVolumeReq) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SetVolumeReq) GetVolume() uint32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PolicyName    string                 `protobuf:"bytes,3,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CurrentState  string                 `protobuf:"bytes,6,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_myb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{12}
}

func (x *Event) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *Event) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *Event) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Event) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

type SessionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	CurrentVolume uint32                 `protobuf:"varint,3,opt,name=current_volume,json=currentVolume,proto3" json:"current_volume,omitempty"`
	TargetPid     uint32                 `protobuf:"varint,4,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	LatencyMs     uint32                 `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatus) Reset() {
	*x = SessionStatus{}
	mi := &file_myb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatus) ProtoMessage() {}

func (x *SessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_myb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatus.ProtoReflect.Descriptor instead.
func (*SessionStatus) Descriptor() ([]byte, []int) {
	return file_myb_proto_rawDescGZIP(), []int{13}
}

func (x *SessionStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SessionStatus) GetCurrentVolume() uint32 {
	if x != nil {
		return x.CurrentVolume
	}
	return 0
}

func (x *SessionStatus) GetTargetPid() uint32 {
	if x != nil {
		return x.TargetPid
	}
	return 0
}

func (x *SessionStatus) GetLatencyMs() uint32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_myb_proto protoreflect.FileDescriptor

const file_myb_proto_rawDesc = "" +
	"\n" +
	"\tmyb.proto\x12\x06myb.v1\"\a\n" +
	"\x05Empty\"\xa4\x01\n" +
	"\fAudioProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fwindow_title\x18\x03 \x01(\tR\vwindowTitle\x12%\n" +
	"\x0ecurrent_volume\x18\x04 \x01(\x02R\rcurrentVolume\x12$\n" +
	"\x0eis_meeting_app\x18\x05 \x01(\bR\fisMeetingApp\"A\n" +
	"\vProcessList\x122\n" +
	"\tprocesses\x18\x01 \x03(\v2\x14.myb.v1.AudioProcessR\tprocesses\"H\n" +
	"\fKeywordMatch\x12\x1a\n" +
	"\bkeywords\x18\x01 \x03(\tR\bkeywords\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x01R\tthreshold\"e\n" +
	"\fPolicyAction\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\rR\x06volume\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\rR\x0fdurationSeconds\x12\x12\n" +
	"\x04then\x18\x03 \x01(\tR\x04then\"v\n" +
	"\x06Policy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x05match\x18\x02 \x01(\v2\x14.myb.v1.KeywordMatchR\x05match\x12,\n" +
	"\x06action\x18\x03 \x01(\v2\x14.myb.v1.PolicyActionR\x06action\" \n" +
	"\n" +
	"PolicyYaml\x12\x12\n" +
	"\x04yaml\x18\x01 \x01(\tR\x04yaml\"8\n" +
	"\x10ValidationResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"O\n" +
	"\x0fStartSessionReq\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12*\n" +
	"\bpolicies\x18\x02 \x03(\v2\x0e.myb.v1.PolicyR\bpolicies\"+\n" +
	"\n" +
	"SessionRef\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"P\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"8\n" +
	"\fSetVolumeReq\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\rR\x06volume\"\xc9\x01\n" +
	"\x05Event\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vpolicy_name\x18\x03 \x01(\tR\n" +
	"policyName\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12#\n" +
	"\rcurrent_state\x18\x06 \x01(\tR\fcurrentState\"\xa9\x01\n" +
	"\rSessionStatus\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12%\n" +
	"\x0ecurrent_volume\x18\x03 \x01(\rR\rcurrentVolume\x12\x1d\n" +
	"\n" +
	"target_pid\x18\x04 \x01(\rR\ttargetPid\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\rR\tlatencyMs2\x95\x03\n" +
	"\fMuteYourBoss\x128\n" +
	"\x12ListAudioProcesses\x12\r.myb.v1.Empty\x1a\x13.myb.v1.ProcessList\x128\n" +
	"\fStartSession\x12\x17.myb.v1.StartSessionReq\x1a\x0f.myb.v1.Session\x120\n" +
	"\vStopSession\x12\x12.myb.v1.SessionRef\x1a\r.myb.v1.Empty\x120\n" +
	"\tSetVolume\x12\x14.myb.v1.SetVolumeReq\x1a\r.myb.v1.Empty\x125\n" +
	"\x0eGetEventStream\x12\x12.myb.v1.SessionRef\x1a\r.myb.v1.Event0\x01\x126\n" +
	"\tGetStatus\x12\x12.myb.v1.SessionRef\x1a\x15.myb.v1.SessionStatus\x12>\n" +
	"\x0eValidatePolicy\x12\x12.myb.v1.PolicyYaml\x1a\x18.myb.v1.ValidationResultB:Z8github.com/HYPERVAPOR/mute-your-boss/gateway/internal/pbb\x06proto3"

var (
	file_myb_proto_rawDescOnce sync.Once
	file_myb_proto_rawDescData []byte
)

func file_myb_proto_rawDescGZIP() []byte {
	file_myb_proto_rawDescOnce.Do(func() {
		file_myb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myb_proto_rawDesc), len(file_myb_proto_rawDesc)))
	})
	return file_myb_proto_rawDescData
}

var file_myb_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_myb_proto_goTypes = []any{
	(*Empty)(nil),            // 0: myb.v1.Empty
	(*AudioProcess)(nil),     // 1: myb.v1.AudioProcess
	(*ProcessList)(nil),      // 2: myb.v1.ProcessList
	(*KeywordMatch)(nil),     // 3: myb.v1.KeywordMatch
	(*PolicyAction)(nil),     // 4: myb.v1.PolicyAction
	(*Policy)(nil),           // 5: myb.v1.Policy
	(*PolicyYaml)(nil),       // 6: myb.v1.PolicyYaml
	(*ValidationResult)(nil), // 7: myb.v1.ValidationResult
	(*StartSessionReq)(nil),  // 8: myb.v1.StartSessionReq
	(*SessionRef)(nil),       // 9: myb.v1.SessionRef
	(*Session)(nil),          // 10: myb.v1.Session
	(*SetVolumeReq)(nil),     // 11: myb.v1.SetVolumeReq
	(*Event)(nil),            // 12: myb.v1.Event
	(*SessionStatus)(nil),    // 13: myb.v1.SessionStatus
}
var file_myb_proto_depIdxs = []int32{
	1,  // 0: myb.v1.ProcessList.processes:type_name -> myb.v1.AudioProcess
	3,  // 1: myb.v1.Policy.match:type_name -> myb.v1.KeywordMatch
	4,  // 2: myb.v1.Policy.action:type_name -> myb.v1.PolicyAction
	5,  // 3: myb.v1.StartSessionReq.policies:type_name -> myb.v1.Policy
	0,  // 4: myb.v1.MuteYourBoss.ListAudioProcesses:input_type -> myb.v1.Empty
	8,  // 5: myb.v1.MuteYourBoss.StartSession:input_type -> myb.v1.StartSessionReq
	9,  // 6: myb.v1.MuteYourBoss.StopSession:input_type -> myb.v1.SessionRef
	11, // 7: myb.v1.MuteYourBoss.SetVolume:input_type -> myb.v1.SetVolumeReq
	9,  // 8: myb.v1.MuteYourBoss.GetEventStream:input_type -> myb.v1.SessionRef
	9,  // 9: myb.v1.MuteYourBoss.GetStatus:input_type -> myb.v1.SessionRef
	6,  // 10: myb.v1.MuteYourBoss.ValidatePolicy:input_type -> myb.v1.PolicyYaml
	2,  // 11: myb.v1.MuteYourBoss.ListAudioProcesses:output_type -> myb.v1.ProcessList
	10, // 12: myb.v1.MuteYourBoss.StartSession:output_type -> myb.v1.Session
	0,  // 13: myb.v1.MuteYourBoss.StopSession:output_type -> myb.v1.Empty
	0,  // 14: myb.v1.MuteYourBoss.SetVolume:output_type -> myb.v1.Empty
	12, // 15: myb.v1.MuteYourBoss.GetEventStream:output_type -> myb.v1.Event
	13, // 16: myb.v1.MuteYourBoss.GetStatus:output_type -> myb.v1.SessionStatus
	7,  // 17: myb.v1.MuteYourBoss.ValidatePolicy:output_type -> myb.v1.ValidationResult
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_myb_proto_init() }
func file_myb_proto_init() {
	if File_myb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myb_proto_rawDesc), len(file_myb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myb_proto_goTypes,
		DependencyIndexes: file_myb_proto_depIdxs,
		MessageInfos:      file_myb_proto_msgTypes,
	}.Build()
	File_myb_proto = out.File
	file_myb_proto_goTypes = nil
	file_myb_proto_depIdxs = nil
}
