// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: myb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MuteYourBoss_ListAudioProcesses_FullMethodName = "/myb.v1.MuteYourBoss/ListAudioProcesses"
	MuteYourBoss_StartSession_FullMethodName       = "/myb.v1.MuteYourBoss/StartSession"
	MuteYourBoss_StopSession_FullMethodName        = "/myb.v1.MuteYourBoss/StopSession"
	MuteYourBoss_SetVolume_FullMethodName          = "/myb.v1.MuteYourBoss/SetVolume"
	MuteYourBoss_GetEventStream_FullMethodName     = "/myb.v1.MuteYourBoss/GetEventStream"
	MuteYourBoss_GetStatus_FullMethodName          = "/myb.v1.MuteYourBoss/GetStatus"
	MuteYourBoss_ValidatePolicy_FullMethodName     = "/myb.v1.MuteYourBoss/ValidatePolicy"
)

// MuteYourBossClient is the client API for MuteYourBoss service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MuteYourBossClient interface {
	ListAudioProcesses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProcessList, error)
	StartSession(ctx context.Context, in *StartSessionReq, opts ...grpc.CallOption) (*Session, error)
	StopSession(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*Empty, error)
	SetVolume(ctx context.Context, in *SetVolumeReq, opts ...grpc.CallOption) (*Empty, error)
	GetEventStream(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	GetStatus(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*SessionStatus, error)
	ValidatePolicy(ctx context.Context, in *PolicyYaml, opts ...grpc.CallOption) (*ValidationResult, error)
}

type muteYourBossClient struct {
	cc grpc.ClientConnInterface
}

func NewMuteYourBossClient(cc grpc.ClientConnInterface) MuteYourBossClient {
	return &muteYourBossClient{cc}
}

func (c *muteYourBossClient) ListAudioProcesses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProcessList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessList)
	err := c.cc.Invoke(ctx, MuteYourBoss_ListAudioProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *muteYourBossClient) StartSession(ctx context.Context, in *StartSessionReq, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, MuteYourBoss_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *muteYourBossClient) StopSession(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MuteYourBoss_StopSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *muteYourBossClient) SetVolume(ctx context.Context, in *SetVolumeReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MuteYourBoss_SetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *muteYourBossClient) GetEventStream(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MuteYourBoss_ServiceDesc.Streams[0], MuteYourBoss_GetEventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionRef, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MuteYourBoss_GetEventStreamClient = grpc.ServerStreamingClient[Event]

func (c *muteYourBossClient) GetStatus(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*SessionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStatus)
	err := c.cc.Invoke(ctx, MuteYourBoss_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *muteYourBossClient) ValidatePolicy(ctx context.Context, in *PolicyYaml, opts ...grpc.CallOption) (*ValidationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, MuteYourBoss_ValidatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MuteYourBossServer is the server API for MuteYourBoss service.
// All implementations must embed UnimplementedMuteYourBossServer
// for forward compatibility.
type MuteYourBossServer interface {
	ListAudioProcesses(context.Context, *Empty) (*ProcessList, error)
	StartSession(context.Context, *StartSessionReq) (*Session, error)
	StopSession(context.Context, *SessionRef) (*Empty, error)
	SetVolume(context.Context, *SetVolumeReq) (*Empty, error)
	GetEventStream(*SessionRef, grpc.ServerStreamingServer[Event]) error
	GetStatus(context.Context, *SessionRef) (*SessionStatus, error)
	ValidatePolicy(context.Context, *PolicyYaml) (*ValidationResult, error)
	mustEmbedUnimplementedMuteYourBossServer()
}

// UnimplementedMuteYourBossServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMuteYourBossServer struct{}

func (UnimplementedMuteYourBossServer) ListAudioProcesses(context.Context, *Empty) (*ProcessList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAudioProcesses not implemented")
}
func (UnimplementedMuteYourBossServer) StartSession(context.Context, *StartSessionReq) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedMuteYourBossServer) StopSession(context.Context, *SessionRef) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSession not implemented")
}
func (UnimplementedMuteYourBossServer) SetVolume(context.Context, *SetVolumeReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVolume not implemented")
}
func (UnimplementedMuteYourBossServer) GetEventStream(*SessionRef, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method GetEventStream not implemented")
}
func (UnimplementedMuteYourBossServer) GetStatus(context.Context, *SessionRef) (*SessionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedMuteYourBossServer) ValidatePolicy(context.Context, *PolicyYaml) (*ValidationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatePolicy not implemented")
}
func (UnimplementedMuteYourBossServer) mustEmbedUnimplementedMuteYourBossServer() {}
func (UnimplementedMuteYourBossServer) testEmbeddedByValue()                      {}

// UnsafeMuteYourBossServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MuteYourBossServer will
// result in compilation errors.
type UnsafeMuteYourBossServer interface {
	mustEmbedUnimplementedMuteYourBossServer()
}

func RegisterMuteYourBossServer(s grpc.ServiceRegistrar, srv MuteYourBossServer) {
	// If the following call panics, it indicates UnimplementedMuteYourBossServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MuteYourBoss_ServiceDesc, srv)
}

func _MuteYourBoss_ListAudioProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MuteYourBossServer).ListAudioProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MuteYourBoss_ListAudioProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MuteYourBossServer).ListAudioProcesses(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MuteYourBoss_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MuteYourBossServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MuteYourBoss_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MuteYourBossServer).StartSession(ctx, req.(*StartSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MuteYourBoss_StopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MuteYourBossServer).StopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MuteYourBoss_StopSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MuteYourBossServer).StopSession(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _MuteYourBoss_SetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVolumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MuteYourBossServer).SetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MuteYourBoss_SetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MuteYourBossServer).SetVolume(ctx, req.(*SetVolumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MuteYourBoss_GetEventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SessionRef)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MuteYourBossServer).GetEventStream(m, &grpc.GenericServerStream[SessionRef, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MuteYourBoss_GetEventStreamServer = grpc.ServerStreamingServer[Event]

func _MuteYourBoss_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MuteYourBossServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MuteYourBoss_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MuteYourBossServer).GetStatus(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _MuteYourBoss_ValidatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyYaml)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MuteYourBossServer).ValidatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MuteYourBoss_ValidatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MuteYourBossServer).ValidatePolicy(ctx, req.(*PolicyYaml))
	}
	return interceptor(ctx, in, info, handler)
}

// MuteYourBoss_ServiceDesc is the grpc.ServiceDesc for MuteYourBoss service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MuteYourBoss_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "myb.v1.MuteYourBoss",
	HandlerType: (*MuteYourBossServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAudioProcesses",
			Handler:    _MuteYourBoss_ListAudioProcesses_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _MuteYourBoss_StartSession_Handler,
		},
		{
			MethodName: "StopSession",
			Handler:    _MuteYourBoss_StopSession_Handler,
		},
		{
			MethodName: "SetVolume",
			Handler:    _MuteYourBoss_SetVolume_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _MuteYourBoss_GetStatus_Handler,
		},
		{
			MethodName: "ValidatePolicy",
			Handler:    _MuteYourBoss_ValidatePolicy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEventStream",
			Handler:       _MuteYourBoss_GetEventStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "myb.proto",
}
